export const SET_CURRENT_LETTER = 'SET_CURRENT_LETTER'
export const ADD_LETTER_TO_CURRENT_WORD = 'ADD_LETTER_TO_CURRENT_WORD'
export const ADD_PHRASE_LETTERS = 'ADD_PHRASE_LETTERS'
export const ADD_WORD_TO_TEXT = 'ADD_WORD_TO_TEXT'