export const SET_CURRENT_LETTER = 'SET_CURRENT_LETTER'
export const REMOVE_LAST_CHARACTER = 'REMOVE_LAST_CHARACTER'
export const ADD_LETTER_TO_CURRENT_WORD = 'ADD_LETTER_TO_CURRENT_WORD'
export const ADD_PHRASE_CODE = 'ADD_PHRASE_CODE'
export const ADD_WORD_TO_TEXT = 'ADD_WORD_TO_TEXT'

export const SET_PREDICTED_WORDS = 'SET_PREDICTED_WORDS'
export const SELECT_PREDICTED_WORD = 'SELECT_PREDICTED_WORD'

export const SET_FETCH_ERROR = 'SET_FETCH_ERROR'
